Testing
snoopsD/RorAdvanced pull request #5
Opened 2017-08-29 07:38 UTC by snoopsD

2017-08-29 07:58 UTC, vkurennov requested changes

2017-08-29 07:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      flash[:notice] = 'Your answer not created'
Тут нужно рендерить страницу вопроса, а не вид answers/create, что произойдет по-умолчанию

2017-08-29 07:58 UTC, vkurennov commented on app/views/answers/create.html.slim
> += render 'form'
Нет, это опять костыль. Все что нужно - это отрендерить страницу вопроса в контроллере. Юзер должен видеть всю старницу, а не просто форму.

2017-08-29 07:58 UTC, vkurennov commented on app/views/answers/destroy.html.slim
> += render 'answer'
Почему при неуспешном удалении, юзер должен видеть только ответ? Какой вы этом смысл. При удалении же нет ошибок валидации, тут можно сделать ребирект с нужным сообщением.

2017-08-29 07:58 UTC, vkurennov commented on app/views/layouts/application.html.slim
> +    = link_to 'Log out', destroy_user_session_path, :method => :delete
У тебя ссылка не под if, не хватает отступа. Т.е. она всегда будет отображаться.
И где ссылка на вход?

2017-08-29 07:58 UTC, vkurennov commented on app/views/questions/new.html.slim
> += form_for @question do |f|
Нужен вывод ошибок валидации

2017-08-29 07:58 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- if user_signed_in? && current_user.owner?(@question)
То есть, у тебя отвечать на вопрос можеть только сам автор вопроса? сам спросил - сам ответил. Сомнительная польза от такой системы.

2017-08-29 07:58 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = link_to 'Delete question', @question, method: :delete, data: { confirm: 'Are you sure?' }
Ага, если это не автор, то он может удалить вопрос. Ну да, чего тут кто-то задает вопросы, на которые я (не автор) не могу отвечать? Удалить нафиг этот вопрос :-)

2017-08-29 07:58 UTC, vkurennov commented on db/migrate/20170825072349_add_user_id_to_question.rb
> +    add_belongs_to :questions, :user
Добавляй еще опцию `foreign_key: true`, чтобы на уровне БД включить контроль целостности.

2017-08-29 07:58 UTC, vkurennov commented on spec/acceptance/answer/delete_answer_spec.rb
> +  scenario 'Authenticated user delete not own answer' do
Нужен похожий тест для незалогиненного юзера

2017-08-29 07:58 UTC, vkurennov commented on spec/acceptance/question/create_question_spec.rb
> +    expect(page).to have_content 'Body can\'t be blank'
Этот тест не должен проходить - у тебя нигде нет вывода ошибок валидации для вопроса. Ты его запускал?

2017-08-29 07:58 UTC, vkurennov commented on spec/acceptance/question/delete_question_spec.rb
> +  scenario 'Authenticated user delete not own question' do
Нужен такой же сценарий для незалогиненного юзера

2017-08-29 07:58 UTC, vkurennov commented on spec/acceptance/answer/new_answer_spec.rb
> +    sign_in(user)
Попробуй здесь создать ответ от другого пользователя, не связанного с вопросом. Чтобы воспроизвести баг с неверным отображением формы.

2017-08-29 07:58 UTC, vkurennov commented on spec/acceptance/question/delete_question_spec.rb
> +    expect(page).to_not have_content 'Delete question'
Вообще, по условиям в виде, у тебя как раз не-автор и видит ссылку. Так что тесты опять же не должны проходить. Не нужно здавать задание с падающими тестами.

2017-08-29 07:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valide attributes' do
Нужен тест на связь созданного ответа с залогиненным юзером

2017-08-29 07:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      before { allow(controller).to receive(:current_user).and_return(user) }
Зачем, ты же делаешь sign_in_user в начале describe? ЗАлогиненный юзер у нас доступен как  `@user`

2017-08-29 07:58 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE#destroy' do
Тут должно быть 2 контекста: для автора и для не-автора. Почему-то в тестах AnswersController ты это сделал, а тут чем ситуация отличается?

2017-08-29 12:19 UTC, snoopsD commented on spec/acceptance/answer/new_answer_spec.rb
> +    sign_in(user)
Не понял задачу. 
Ответ может ведь создать любой зарегистрированный пользователь, а незарегистрированному просто не показывается кнопка Ответить.

2017-08-29 12:21 UTC, snoopsD commented on app/views/layouts/application.html.slim
> +    = link_to 'Log out', destroy_user_session_path, :method => :delete
Здесь у меня затык. Когда я добавляю ссылка Log in, rspec ругается, что идет находится две копии контента 'Log in'. И я не понимаю, откуда лезет первая копия, поэтому пришлось удалить ссылку, но я пытаюсь найти. Мне кажется, что это связано с layout'ом, но пока не уверен.

2017-08-29 19:02 UTC, vkurennov requested changes

2017-08-29 19:02 UTC, vkurennov commented on app/views/layouts/application.html.slim
> +    - if user_signed_in?
Ну а на вход-то ссылка где?

2017-08-29 19:02 UTC, vkurennov commented on app/views/questions/show.html.slim
> += render 'common/errors', resource: @question
А здесь еще зачем раз ошибки выводить? У тебя же в паршале форм они выводятся

2017-08-29 19:02 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- if user_signed_in? && current_user.owner?(@question)
На user_signed_in? уже была проверка, можно было вложенным if сделать

2017-08-29 19:02 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: question, answer: attributes_for(:answer) } }.to change(@user.answers, :count).by(1)
Ну так тест на связь с вопросом тоже нужен, зачем же его удалять? Нужно 2 теста: и на связь с вопросом и на связь с юзером, одно другое не исключает

2017-08-29 19:02 UTC, vkurennov commented on spec/acceptance/sign/sign_in_spec.rb
> +    sign_in(user)
Тут надо полный тест сделать: юзер заходит на главную, кликает на ссылку "Войти", вводит данные и т.д. А то ты так пропустил наличие ссылки "Войти" на страницах.

2017-08-30 08:00 UTC, vkurennov requested changes

2017-08-30 08:00 UTC, vkurennov commented on spec/acceptance/sign/sign_in_spec.rb
> +    sign_in(user)
Не исправлено, у тебя по-прежнему используется хелпер sign_in, а тут надо написать сценарий без него.

2017-08-30 08:00 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valide attributes' do
У тебя уже есть этот контекст, зачем его снова писать? Т.е. в одном контексте "with valid attributes" должно быть 3 теста:

 - На связь ответа с вопросом
 - На связь ответа с залогиненным юзером
 - На редирект

2017-08-30 08:00 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it 'redirect to view question with answer' do
у тебя уже есть такой тест, дублирование

2017-08-30 09:28 UTC, vkurennov requested changes

2017-08-30 09:28 UTC, vkurennov commented on spec/acceptance/sign/sign_in_spec.rb
> +    visit new_user_session_path
Ну так смысл-то в другом был: кликнуть по ссылке Login c главной, а не сразу зайти на страницу входа. Т.е. проверить, что юзер может зайти с главной на страницу логина

2017-08-30 09:28 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>          expect { post :create, params: { question_id: question, answer: attributes_for(:answer) } }.to change(Answer.where(question: question), :count).by(1)
А теперь вспоминаем про ассоциации question, и пишем нормальный код в change

2017-08-30 12:25 UTC, vkurennov approved these changes

2017-08-30 12:31 UTC, merged